### ISSUE TITLE
How do I implement the custom energy?

### ISSUE THREAD

**Issue by lc82111** [marciojmo/MSnakes#2]
Clear Code. Great Work. Thanks.
A litter question:
How do I implement the custom energy that makes the evolution toward a specific direction e.g. the normal direction?
Thank you.

**Comment by marciojmo** [comment]
Hi! Thanks for the compliments..

I implemented this algorithm for a master's degree class work in computer vision a few years ago but unfortunatelly I've dropped out and don't remember much of it. Although I cannot help you, some great people have forked this repository and I guess you may find your answer in their implementations! Best wishes!

**Comment by lc82111** [comment]
Thank you.
